name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
# I've avoided matrix here because it looks
# like the parallel jobs don't run in isolation
# and then they interfere with each other
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup .NET for integration testing
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: üü¢ Setup NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: '20'

      - name: Disable man-db to make package install and removal faster
        run: |
          echo 'set man-db/auto-update false' | sudo debconf-communicate >/dev/null
          sudo dpkg-reconfigure man-db          

      - name: ‚¨ÜÔ∏è Fetch latest software lists
        run: |
          sudo apt update -q

      - name: üü• Setup Redis for test locks
        run: |
          sudo apt install redis-server -q

      - name: Test
        env:
          SUPPRESS_DOWNLOAD_PROGRESS: 1
          RUNNING_IN_GITHUB_ACTION: 1
          TEST_TIMEOUT: 60000
          MAX_WORKERS: 1
        run: |
          dotnet nuget add source --name github-fluffynuts --username '${{ github.actor }}' --password '${{ github.token }}' --store-password-in-clear-text https://nuget.pkg.github.com/fluffynuts/index.json
          npm ci
          npm run build
          npm test
